import { useEffect, useRef, useState } from 'react'
import { BrowserRouter, NavLink, Navigate, Route, Routes, useLocation } from 'react-router-dom'
import { motion, useMotionValue, useSpring } from 'framer-motion'
import { Award, BarChart3, Battery, Check, ChevronRight, CircleUserRound, ClipboardCheck, Clock3, HeartPulse, Home, Lightbulb, LockKeyhole, LogOut, Menu, Plus, Sparkles, Target, Trash2, Trophy, X, Zap } from 'lucide-react'
import './App.css'
import './systems.css'

const today = '2026-09-27'
const initialTasks = [
  { id: 1, title: 'Finish research methods outline', subject: 'Research Methods', deadline: today, priority: 'High', energyCost: 'high', completed: false },
  { id: 2, title: 'Submit calculus problem set', subject: 'Calculus II', deadline: today, priority: 'Medium', energyCost: 'medium', completed: false },
  { id: 3, title: 'Read chapter 6 before seminar', subject: 'Sociology', deadline: '2026-09-29', priority: 'Low', completed: true },
  { id: 4, title: 'Prepare biology flashcards', subject: 'Biology', deadline: '2026-10-01', priority: 'Medium', energyCost: 'low', completed: false },
]
const initialWellness = { mood: 4, stress: 2 }
const moods = [{ value: 1, emoji: '😔', label: 'Low' }, { value: 2, emoji: '😕', label: 'Off' }, { value: 3, emoji: '😐', label: 'Okay' }, { value: 4, emoji: '🙂', label: 'Good' }, { value: 5, emoji: '🌞', label: 'Bright' }]
const achievementDefinitions = [
  { id: 'first-step', title: 'First Step', description: 'Complete your first task.', icon: '🌱', target: 1, progress: tasks => Math.min(tasks.filter(task => task.completed).length, 1) },
  { id: 'on-a-roll', title: 'On a Roll', description: 'Complete three tasks.', icon: '🔥', target: 3, progress: tasks => Math.min(tasks.filter(task => task.completed).length, 3) },
  { id: 'deadline-slayer', title: 'Deadline Slayer', description: 'Finish five tasks before their deadline.', icon: '⚡', target: 5, progress: tasks => Math.min(tasks.filter(task => task.completed && (!task.completedAt || task.completedAt <= task.deadline)).length, 5) },
  { id: 'steady-hand', title: 'Steady Hand', description: 'Keep your energy above 50.', icon: '🌿', target: 1, progress: (_, energy) => energy > 50 ? 1 : 0 },
  { id: 'consistent', title: 'Consistent', description: 'Show up and check in today.', icon: '☀️', target: 1, progress: (_, __, energyState) => energyState?.date === today ? 1 : 0 },
  { id: 'balanced', title: 'Balanced Day', description: 'Complete a task and wellness check in.', icon: '🫶', target: 2, progress: (tasks, _, energyState, wellness) => Number(tasks.some(task => task.completed)) + Number(Boolean(energyState?.date === today && wellness)) },
]

function useStored(key, fallback) {
  const [value, setValue] = useState(() => { try { return JSON.parse(localStorage.getItem(key)) || fallback } catch { return fallback } })
  useEffect(() => {
    const receive = event => { if (event.detail?.key === key) setValue(event.detail.value) }
    window.addEventListener('studentEase:store', receive)
    return () => window.removeEventListener('studentEase:store', receive)
  }, [key])
  const update = next => setValue(current => { const updated = typeof next === 'function' ? next(current) : next; localStorage.setItem(key, JSON.stringify(updated)); window.dispatchEvent(new CustomEvent('studentEase:store', { detail: { key, value: updated } })); return updated })
  useEffect(() => localStorage.setItem(key, JSON.stringify(value)), [key, value])
  return [value, update]
}

function effectiveEnergy(energyState, tasks) { return Math.max(0, Math.min(100, (energyState?.level ?? 70) - tasks.filter(task => task.completed && task.completedAt === today).length * 4)) }
function buildAchievements(tasks, energyState, wellness, saved) { return achievementDefinitions.map(definition => { const progress = definition.progress(tasks, effectiveEnergy(energyState, tasks), energyState, wellness); const existing = saved.find(item => item.id === definition.id); return { ...definition, progress, unlockedAt: existing?.unlockedAt || (progress >= definition.target ? today : null) } }) }
function assistantSuggestions(tasks, energy, wellness, recentlyUnlocked) { const suggestions = []; const dueSoon = tasks.filter(task => !task.completed && task.deadline <= today); const highEnergy = tasks.filter(task => !task.completed && task.energyCost === 'high'); const overdue = tasks.filter(task => !task.completed && task.deadline < today).length; if (recentlyUnlocked) suggestions.push(`You unlocked ${recentlyUnlocked.title}. That consistency is doing real work.`); if (energy < 45 && highEnergy.length) suggestions.push(`Your energy is ${energy}%. Start with a smaller task, then save the heavier work for a better window.`); if (dueSoon.length) suggestions.push(`${dueSoon[0].title} needs attention today. A focused 20-minute start is enough.`); if (overdue > 1) suggestions.push('There are a few overdue tasks. Try breaking the oldest one into a ten-minute first step.'); if (wellness?.stress >= 4) suggestions.push('Your stress check is elevated. Take a short reset before choosing your next task.'); return suggestions.slice(0, 3).length ? suggestions.slice(0, 3) : ['Your plan has room to breathe. Choose one meaningful task and begin gently.'] }

function CustomCursor() {
  const [state, setState] = useState('default'); const [enabled, setEnabled] = useState(false); const [ripples, setRipples] = useState([]); const id = useRef(0)
  const x = useMotionValue(-100); const y = useMotionValue(-100); const sx = useSpring(x, { damping: 30, stiffness: 420, mass: .35 }); const sy = useSpring(y, { damping: 30, stiffness: 420, mass: .35 })
  useEffect(() => { const media = matchMedia('(pointer: fine) and (prefers-reduced-motion: no-preference)'); const update = () => setEnabled(media.matches); update(); media.addEventListener('change', update); return () => media.removeEventListener('change', update) }, [])
  useEffect(() => { if (!enabled) return; const move = e => { x.set(e.clientX); y.set(e.clientY); setState(e.target.closest('[data-cursor]')?.dataset.cursor || 'default') }; const click = e => { const ripple = { id: id.current++, x: e.clientX, y: e.clientY }; setRipples(r => [...r, ripple]); setTimeout(() => setRipples(r => r.filter(item => item.id !== ripple.id)), 500) }; addEventListener('mousemove', move); addEventListener('click', click); return () => { removeEventListener('mousemove', move); removeEventListener('click', click) } }, [enabled, x, y])
  if (!enabled) return null
  return <><motion.div className={`cursor-ring cursor-${state}`} style={{ x: sx, y: sy }} /><motion.div className="cursor-dot" style={{ x, y }} />{ripples.map(r => <motion.div key={r.id} className="cursor-ripple" initial={{ x: r.x, y: r.y, scale: .2, opacity: .7 }} animate={{ scale: 1.8, opacity: 0 }} transition={{ duration: .5 }} />)}</>
}

function Card({ children, className = '', ...props }) { return <motion.div whileHover={{ y: -3, scale: 1.008 }} transition={{ type: 'spring', stiffness: 300, damping: 24 }} data-cursor="card" className={`card ${className}`} {...props}>{children}</motion.div> }
function Button({ children, className = '', ...props }) { return <button data-cursor="action" className={`button ${className}`} {...props}>{children}</button> }
function Layout({ user, onLogout }) {
  const location = useLocation(); const [open, setOpen] = useState(false)
  const nav = [{ to: '/', label: 'Overview', icon: Home }, { to: '/tasks', label: 'Tasks', icon: ClipboardCheck }, { to: '/wellness', label: 'Wellness', icon: HeartPulse }, { to: '/habits', label: 'Habits', icon: Target }, { to: '/planner', label: 'Study planner', icon: Clock3 }, { to: '/achievements', label: 'Achievements', icon: Trophy }]
  return <div className="app-shell"><aside className={open ? 'sidebar open' : 'sidebar'}><div className="logo"><span><Sparkles size={16} /></span> StudentEase</div><p className="side-label">Your space</p><nav>{nav.map(({ to, label, icon: Icon }) => <NavLink key={to} to={to} onClick={() => setOpen(false)} className={({ isActive }) => isActive ? 'active' : ''}><Icon size={17} />{label}</NavLink>)}</nav><div className="side-bottom"><NavLink to="/profile" className={location.pathname === '/profile' ? 'active' : ''}><CircleUserRound size={17} />Profile</NavLink><button data-cursor="action" className="logout" onClick={onLogout}><LogOut size={17} />Log out</button></div></aside><button className="mobile-menu" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button><main className="main-area"><header className="topbar"><div><p className="date-label">Sunday, September 27, 2026</p><h1>{location.pathname === '/' ? `Good morning, ${user.name.split(' ')[0]}` : nav.find(n => n.to === location.pathname)?.label || 'Profile'}</h1></div><div className="avatar">{user.name.split(' ').map(n => n[0]).join('').slice(0, 2)}</div></header><Routes><Route path="/" element={<Dashboard />} /><Route path="/tasks" element={<Tasks />} /><Route path="/wellness" element={<Wellness />} /><Route path="/habits" element={<Habits />} /><Route path="/planner" element={<Planner />} /><Route path="/achievements" element={<Achievements />} /><Route path="/profile" element={<Profile user={user} onLogout={onLogout} />} /><Route path="*" element={<Navigate to="/" />} /></Routes></main></div>
}

function Dashboard() {
  const [tasks] = useStored('tasks', initialTasks); const [wellness] = useStored('wellness', initialWellness); const done = tasks.filter(t => t.completed).length; const todayTasks = tasks.filter(t => t.deadline === today); const upcoming = tasks.filter(t => t.deadline > today).slice(0, 3)
  return <div className="page"><section className="welcome-banner"><div><p className="eyebrow">Sunday reset</p><h2>A little progress<br />goes a long way.</h2><p>Keep your day light, focused, and yours.</p></div><div className="sun-mark">☼</div></section><div className="section-heading"><div><p className="eyebrow">Your rhythm</p><h2>Today at a glance</h2></div><NavLink to="/tasks" className="text-link" data-cursor="action">View all tasks <ChevronRight size={15} /></NavLink></div><div className="dashboard-grid"><Card className="tasks-card"><div className="card-head"><h3>Today's tasks</h3><span className="count-pill">{done}/{tasks.length} done</span></div>{todayTasks.length ? todayTasks.map(task => <TaskRow key={task.id} task={task} />) : <p className="muted">Nothing due today. Enjoy the breathing room.</p>}</Card><Card className="wellness-card"><div className="card-head"><h3>Wellness check</h3><HeartPulse size={18} /></div><div className="wellness-score"><span>{moods.find(m => m.value === wellness.mood)?.emoji || '🙂'}</span><div><strong>{moods.find(m => m.value === wellness.mood)?.label || 'Good'}</strong><p>Stress feels {wellness.stress <= 2 ? 'manageable' : 'a little high'} today.</p></div></div><NavLink to="/wellness" className="soft-link" data-cursor="action">Check in <ChevronRight size={14} /></NavLink></Card><Card className="study-card"><div className="card-head"><h3>Study hours</h3><span className="trend">+12%</span></div><div className="chart"><div className="chart-bars">{[42, 65, 48, 78, 58, 88, 36].map((height, i) => <div key={i} className="bar-wrap"><div className="bar" style={{ height: `${height}%` }} /><span>{['M', 'T', 'W', 'T', 'F', 'S', 'S'][i]}</span></div>)}</div><strong>8.4 <small>hours this week</small></strong></div></Card><Card className="exams-card"><div className="card-head"><h3>Coming up</h3><BarChart3 size={18} /></div>{upcoming.map(task => <div className="exam-row" key={task.id}><div><strong>{task.title}</strong><span>{task.subject}</span></div><b>{Math.max(1, Math.ceil((new Date(task.deadline) - new Date(today)) / 86400000))}d</b></div>)}</Card></div><SystemsStrip /></div>
}
function SystemsStrip() {
  const [tasks] = useStored('tasks', initialTasks); const [wellness] = useStored('wellness', initialWellness); const [energyState, setEnergyState] = useStored('energyLevel', { date: today, level: 70 }); const [saved, setSaved] = useStored('achievements', []); const [dismissed, setDismissed] = useState([]); const [toast, setToast] = useState(null); const energy = effectiveEnergy(energyState, tasks); const achievements = buildAchievements(tasks, energyState, wellness, saved); const newlyUnlocked = achievements.find(item => item.unlockedAt && !saved.some(savedItem => savedItem.id === item.id)); const suggestions = assistantSuggestions(tasks, energy, wellness, newlyUnlocked)
  useEffect(() => { if (!newlyUnlocked) return undefined; const timer = window.setTimeout(() => { setSaved(achievements.filter(item => item.unlockedAt).map(({ id, title, description, icon, unlockedAt, progress }) => ({ id, title, description, icon, unlockedAt, progress }))); setToast(newlyUnlocked) }, 0); return () => window.clearTimeout(timer) }, [newlyUnlocked, achievements, setSaved])
  const levelClass = energy < 35 ? 'low' : energy < 65 ? 'medium' : 'high'
  return <><div className="systems-grid"><Card className="energy-card"><div className="system-title"><div><p className="eyebrow">Your capacity</p><h3>Energy today</h3></div><Battery size={20} /></div><div className="energy-readout"><strong>{energy}</strong><span>/ 100</span></div><div className={`energy-track ${levelClass}`}><span style={{ width: `${energy}%` }} /></div><label className="energy-checkin">Reset with a check-in<input data-cursor="action" type="range" min="0" max="100" value={energyState?.date === today ? energyState.level : 70} onChange={event => setEnergyState({ date: today, level: Number(event.target.value) })} /></label></Card><Card className="achievement-summary"><div className="system-title"><div><p className="eyebrow">Small wins</p><h3>Achievements</h3></div><Award size={20} /></div><div className="achievement-total"><strong>{achievements.filter(item => item.unlockedAt).length}</strong><span>/ {achievements.length} unlocked</span></div><NavLink to="/achievements" className="soft-link" data-cursor="action">See your wins <ChevronRight size={14} /></NavLink></Card><Card className="assistant-card"><div className="system-title"><div><p className="eyebrow">A little help</p><h3>Smart assistant</h3></div><Lightbulb size={20} /></div><div className="assistant-list">{suggestions.map((suggestion, index) => !dismissed.includes(index) && <div className="assistant-suggestion" key={suggestion}><Zap size={14} /><p>{suggestion}</p><button data-cursor="action" aria-label="Dismiss suggestion" onClick={() => setDismissed([...dismissed, index])}><X size={13} /></button></div>)}</div></Card></div>{toast && <motion.div className="achievement-toast" initial={{ opacity: 0, y: -12 }} animate={{ opacity: 1, y: 0 }}><span>{toast.icon}</span><div><strong>Achievement unlocked</strong><p>{toast.title}</p></div><button data-cursor="action" onClick={() => setToast(null)}><X size={14} /></button></motion.div>}</>
}
function EnergyFlag({ task }) { const [energyState] = useStored('energyLevel', { date: today, level: 70 }); const [tasks] = useStored('tasks', initialTasks); return energyState && effectiveEnergy(energyState, tasks) < 35 && task.energyCost === 'high' && !task.completed ? <span className="energy-flag">Maybe not today</span> : null }
function TaskRow({ task, onToggle }) { return <div className={`task-row ${task.completed ? 'completed' : ''}`}><button className="check" data-cursor="action" onClick={() => onToggle?.(task.id)}>{task.completed && <Check size={13} />}</button><div><strong>{task.title}</strong><span>{task.subject} · {task.deadline === today ? 'Due today' : task.deadline}</span></div><i className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</i><EnergyFlag task={task} /></div> }
function Tasks() { const [tasks, setTasks] = useStored('tasks', initialTasks); const [filter, setFilter] = useState('All'); const [showForm, setShowForm] = useState(false); const [form, setForm] = useState({ title: '', subject: '', deadline: today, priority: 'Medium', energyCost: 'medium' }); const filtered = tasks.filter(t => filter === 'All' || t.priority === filter); const toggle = id => setTasks(tasks.map(t => t.id === id ? { ...t, completed: !t.completed, completedAt: !t.completed ? today : null } : t)); const add = e => { e.preventDefault(); if (!form.title.trim()) return; setTasks([...tasks, { ...form, id: Date.now(), completed: false }]); setForm({ title: '', subject: '', deadline: today, priority: 'Medium', energyCost: 'medium' }); setShowForm(false) }; return <div className="page"><div className="page-intro"><div><p className="eyebrow">Make it visible</p><h2>All tasks</h2><p className="muted">One clear next step at a time.</p></div><Button onClick={() => setShowForm(!showForm)}><Plus size={17} /> Add task</Button></div>{showForm && <form className="card task-form" onSubmit={add}><input data-cursor="text" placeholder="What needs your attention?" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} autoFocus /><input data-cursor="text" placeholder="Subject" value={form.subject} onChange={e => setForm({ ...form, subject: e.target.value })} /><input data-cursor="text" type="date" value={form.deadline} onChange={e => setForm({ ...form, deadline: e.target.value })} /><select data-cursor="action" value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })}><option>Low</option><option>Medium</option><option>High</option></select><select data-cursor="action" value={form.energyCost} onChange={e => setForm({ ...form, energyCost: e.target.value })}><option value="low">Low energy</option><option value="medium">Medium energy</option><option value="high">High energy</option></select><Button>Add task</Button></form>}<div className="filter-bar">{['All', 'High', 'Medium', 'Low'].map(item => <button data-cursor="action" className={filter === item ? 'filter active' : 'filter'} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><div className="task-list card">{filtered.map(task => <div className="task-with-delete" key={task.id}><TaskRow task={task} onToggle={toggle} /><button className="icon-button" data-cursor="action" onClick={() => setTasks(tasks.filter(t => t.id !== task.id))}><Trash2 size={15} /></button></div>)}</div></div> }
function Achievements() { const [tasks] = useStored('tasks', initialTasks); const [wellness] = useStored('wellness', initialWellness); const [energyState] = useStored('energyLevel', { date: today, level: 70 }); const [saved, setSaved] = useStored('achievements', []); const achievements = buildAchievements(tasks, energyState, wellness, saved); useEffect(() => { const unlocked = achievements.filter(item => item.unlockedAt).map(({ id, title, description, icon, unlockedAt, progress }) => ({ id, title, description, icon, unlockedAt, progress })); if (unlocked.length !== saved.length || unlocked.some(item => !saved.some(existing => existing.id === item.id))) setSaved(unlocked) }, [achievements, saved, setSaved]); return <div className="page"><div className="page-intro"><div><p className="eyebrow">Proof of progress</p><h2>Your achievements</h2><p className="muted">The small things are adding up.</p></div><div className="streak"><strong>{achievements.filter(item => item.unlockedAt).length}</strong><span>unlocked</span></div></div><div className="achievement-grid">{achievements.map(item => <Card className={item.unlockedAt ? 'achievement unlocked' : 'achievement locked'} key={item.id}><div className="achievement-icon">{item.unlockedAt ? item.icon : <LockKeyhole size={20} />}</div><div><h3>{item.title}</h3><p>{item.description}</p><div className="achievement-progress"><span style={{ width: `${Math.min(100, item.progress / item.target * 100)}%` }} /></div><small>{item.unlockedAt ? `Unlocked ${item.unlockedAt}` : `${item.progress} / ${item.target}`}</small></div></Card>)}</div></div> }
function Wellness() { const [wellness, setWellness] = useStored('wellness', initialWellness); const [saved, setSaved] = useState(false); return <div className="page narrow"><div className="page-intro"><div><p className="eyebrow">A daily pause</p><h2>How are you, really?</h2><p className="muted">There is no right answer. Just an honest one.</p></div><span className="breathing-dot" /></div><Card className="mood-panel"><h3>Choose the closest feeling</h3><div className="mood-options">{moods.map(m => <button data-cursor="action" className={wellness.mood === m.value ? 'mood selected' : 'mood'} key={m.value} onClick={() => { setWellness({ ...wellness, mood: m.value }); setSaved(false) }}><span>{m.emoji}</span><small>{m.label}</small></button>)}</div></Card><Card className="stress-panel"><div className="card-head"><div><h3>Stress level</h3><p className="muted">Move the dial gently. This helps shape your suggestions.</p></div><strong className="stress-number">{wellness.stress}<small>/ 5</small></strong></div><input data-cursor="action" className="stress-slider" type="range" min="1" max="5" value={wellness.stress} onChange={e => { setWellness({ ...wellness, stress: Number(e.target.value) }); setSaved(false) }} /><div className="range-labels"><span>Peaceful</span><span>Overloaded</span></div></Card><div className="suggestions"><p className="eyebrow">For this moment</p><h3>Small ways to soften the edges</h3><div className="suggestion-grid">{['Take five slow breaths before your next task.', 'Put your phone across the room for 20 minutes.', 'Step outside and notice three colors.', 'Drink a glass of water, then begin again.'].slice(0, wellness.stress >= 4 ? 4 : 3).map((tip, i) => <Card className="tip" key={tip}><span>0{i + 1}</span><p>{tip}</p></Card>)}</div></div><Button className="save-button" onClick={() => setSaved(true)}>{saved ? <><Check size={16} /> Saved for today</> : 'Save check-in'}</Button></div> }
function Habits() { const [habits, setHabits] = useStored('habits', [{ id: 1, name: 'Sleep 7+ hours', done: true }, { id: 2, name: 'Move your body', done: false }, { id: 3, name: 'Study with intention', done: true }, { id: 4, name: 'Drink enough water', done: false }]); const toggle = id => setHabits(habits.map(h => h.id === id ? { ...h, done: !h.done } : h)); return <div className="page"><div className="page-intro"><div><p className="eyebrow">Tiny promises</p><h2>Habits that hold you</h2><p className="muted">Today is one tile in a bigger pattern.</p></div><div className="streak"><strong>4</strong><span>day streak</span></div></div><Card className="habit-card"><div className="week-row">{['M', 'T', 'W', 'T', 'F', 'S', 'S'].map((day, i) => <div key={i} className={i < 5 ? 'day done' : i === 5 ? 'day today' : 'day'}><span>{day}</span><i /></div>)}</div><div className="habit-list">{habits.map(h => <button data-cursor="action" className={h.done ? 'habit done' : 'habit'} key={h.id} onClick={() => toggle(h.id)}><span className="habit-check">{h.done && <Check size={14} />}</span><strong>{h.name}</strong><ChevronRight size={16} /></button>)}</div></Card></div> }
function Planner() { const subjects = ['Research Methods', 'Calculus II', 'Sociology']; return <div className="page"><div className="page-intro"><div><p className="eyebrow">Make time for what matters</p><h2>Study planner</h2><p className="muted">A flexible rhythm beats a perfect plan.</p></div><Button><Plus size={17} /> Add session</Button></div><Card className="planner-card"><div className="planner-head"><h3>This week</h3><span className="count-pill">3 sessions planned</span></div><div className="timetable">{['Mon', 'Tue', 'Wed', 'Thu', 'Fri'].map((day, i) => <div className="time-column" key={day}><span>{day}</span><div className={i === 1 ? 'time-slot coral' : i === 3 ? 'time-slot mint' : 'time-slot empty'} data-cursor="drag">{i === 1 ? <><strong>Calculus II</strong><small>10:00 · 45 min</small></> : i === 3 ? <><strong>Sociology</strong><small>14:00 · 60 min</small></> : <small>Open</small>}</div></div>)}</div></Card><div className="section-heading"><div><p className="eyebrow">Your subjects</p><h3>Focus areas</h3></div></div><div className="subject-list">{subjects.map((subject, i) => <Card className="subject" key={subject}><span className={`subject-dot dot-${i}`} /><strong>{subject}</strong><span>{i + 2} sessions</span></Card>)}</div></div> }
function Profile({ user, onLogout }) { return <div className="page narrow"><p className="eyebrow">Your space</p><h2>Profile</h2><Card className="profile-card"><div className="profile-avatar">{user.name.split(' ').map(n => n[0]).join('').slice(0, 2)}</div><h3>{user.name}</h3><p className="muted">{user.email}</p><div className="profile-setting"><span>Daily gentle reminder</span><input type="checkbox" defaultChecked /></div><div className="profile-setting"><span>Reduce motion</span><input type="checkbox" /></div><Button className="outline-button" onClick={onLogout}><LogOut size={16} /> Log out</Button></Card></div> }
function Auth({ onLogin }) { const [name, setName] = useState('Alex Morgan'); const [email, setEmail] = useState('alex@example.com'); return <main className="auth"><div className="auth-art"><div className="logo"><span><Sparkles size={16} /></span> StudentEase</div><div><p className="eyebrow">Your calm command center</p><h1>Make room for<br /><em>your whole life.</em></h1><p>Tasks, study, habits, and wellness in one kinder rhythm.</p></div><span className="auth-orbit">✦</span></div><form className="auth-form" onSubmit={e => { e.preventDefault(); onLogin({ name, email }) }}><p className="eyebrow">Welcome back</p><h2>Begin where you are.</h2><label>Name<input data-cursor="text" value={name} onChange={e => setName(e.target.value)} /></label><label>Email<input data-cursor="text" type="email" value={email} onChange={e => setEmail(e.target.value)} /></label><Button>Enter StudentEase <ChevronRight size={16} /></Button><p className="auth-note">No account needed for this demo. Your data stays in this browser.</p></form></main> }
export default function App() { const [user, setUser] = useStored('user', null); return <BrowserRouter><CustomCursor />{user ? <Layout user={user} onLogout={() => setUser(null)} /> : <Auth onLogin={setUser} />}</BrowserRouter> }
